    name: testPlugin
    main: kr.ac.ssu.artistum.testPlugin
    version: 0.0.0
	commands:
	  basic:
	    description: This is a demo command.
	    usage: /<command> [player]
	    permission: <plugin name>.basic
	    permission-message: You don't have <permission>